### ISSUE TITLE
GitHub Discussions

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports#13]
## Abstract

GitHub Universe 2020 で Discussions のパブリックベータがアナウンスされました。
https://github.blog/2020-12-08-new-from-universe-2020-dark-mode-github-sponsors-for-companies-and-more/

すでに [Google Group](https://groups.google.com/g/thinreports?pli=1) にディスカッショングループがありますが、これを GitHub Discussions に切り替えたいと思います。

## Introduction of GitHub Discussions

Discussions を有効にすると、そのリポジトリに「Discussions」タブが表示されます (既にうっかり有効にしてありますがまだ使わないで)。

![image](https://user-images.githubusercontent.com/739339/101628690-83a90e80-3a63-11eb-9a0e-8bc084b937af.png)

実際にどんな感じになるかは、既に使っているリポジトリを見てください。例えば prawn も参考になるかもしれません。
https://github.com/prawnpdf/prawn/discussions

## Details

Discussions グループの運用は次のものを考えています。

- [thinreports/thinreports](https://github.com/thinreports/thinreports) に Discussions を作成する (GitHub Discussions はリポジトリ単位で作ることができる)
- 話題 (thinreports-generator, thinreports-editor, etc) はラベルで区別する
- 主要なプロダクトのリポジトリの README に Discussions へのリンクを貼る
- Issue vs. Discussions? は次の通り。また、この内容は `CONTRIBUTING.md` を作成し明記しておく
  - Issue ... バグ報告、機能提案
  - Discussions ... 使い方の質問 (Q&A)、アイデアの投稿 (Ideas)、アナウンス (Announcement)

既存の [Google Goups](https://groups.google.com/g/thinreports?pli=1) は次のようにします。

- 移行したことを投稿してメンバーに知らせ、今後は GitHub Discussions を使って欲しい旨連絡する
- 当面の間は両方運用するが、様子をみて閉鎖も検討する

**Comment by hidakatsuya** [comment]
@maeda-m いかがですか？

**Comment by hidakatsuya** [comment]
特に反対意見がなければ、このまま Discussions をセットアップしようと思います。

**Comment by maeda-m** [comment]
@hidakatsuya メッセージありがとうございます。

> すでに Google Group にディスカッショングループがありますが、これを GitHub Discussions に切り替えたいと思います。

なるほど、賛成です。

> Discussions グループの運用は次のものを考えています。
> 既存の Google Goups は次のようにします。

なんか、Githubで完結すると情報がまとまる感じがしていいと思いました。
Discussions であれば Issue に書くほどじゃない、アイディア等（ 暗黙知的なものも？）が共有しやすくなりますね。

**Comment by hidakatsuya** [comment]
よーし、では description の方針でセットアップしていきますね

**Comment by hidakatsuya** [comment]
GitHub Discussions をセットアップしました。
https://github.com/thinreports/thinreports/discussions

> * 話題 (thinreports-generator, thinreports-editor, etc) はラベルで区別する

generator, editor など、ラベル等 (カテゴリ) での話題を区別することについては、一旦しない方向にします。今後、利用状況をみつつ、必要なら導入していきます。

**Comment by hidakatsuya** [comment]
https://github.com/thinreports/thinreports/commit/cdc1e0063c736e967bebbf75a405f447fe9f6488 で、README に GitHub Discussions のリンクを追記

**Comment by hidakatsuya** [comment]
Google Groups にて、GitHub Discussions のアナウンスと今後の方針についてのメッセージを投稿した
https://groups.google.com/g/thinreports/c/6gsRluRF4vs

**Comment by hidakatsuya** [comment]
> * 主要なプロダクトのリポジトリの README に Discussions へのリンクを貼る

下記、リポジトリの README に GitHub Discussions へのリンクを追記した

- thinreports/thinreports (このリポジトリ)
- thinreports/thinreports-generator
- thinreports/thinreports-editor

**Comment by hidakatsuya** [comment]
> Issue vs. Discussions? は次の通り。また、この内容は `CONTRIBUTING.md` を作成し明記しておく

とりあえず、https://github.com/thinreports/thinreports-generator/commit/e4521b481c322bd1d90eafa52afdd361f2d8eb66 で generator の CONTRIBUTING.md の Discussion Group を GitHub Discussions へ変更した。

**Comment by hidakatsuya** [comment]
@maeda-m 一通り対応したので、この issue は閉じますね。

**Comment by maeda-m** [comment]
@hidakatsuya はい。対応ありがとうございました。
