### ISSUE TITLE
Goal of the first release version of the Section format and how to proceed with its development

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports#23]
https://github.com/thinreports/thinreports/issues/12 で実装された Section Report フォーマットの正式版リリースに向けて、何をゴールとしどのように進めていくかの基本的な方針をまとめてみました。

まずはこのレベルで認識を合わせた後に、具体的な作業を進めていきたいと思います。なお、この提案は #12 の Future Development をベースにしています。

## 基本方針

- コアメンバー以外の誰でも開発や方針策定に参加できるようにする
  - コアメンバー ( @maeda-m @hidakatsuya ) だけでは絶対に達成できません。
- 使える (試せる) ようにする
  - 簡単に試せないと興味を持つこともできません。
- リリースは小さく頻繁に
  - 作ったものをできるだけ早く使えるようにすることで、より使ってもらうことができ、より多くのフィードバックも得られるはずです。

### 現状でリリースする

現状でも基本的に使えるので、ドキュメントの整備など最低限の対応を行ったらリリースします。

その場合のバージョン番号は要検討ですが、直近の正式版のリリースバージョンを  `v1.0.0` とすると、
```
Tag: v1.0.0-dev.<タイムスタンプ>
Package filename: thinreports-section-editor-1.0.0-dev.<タイムスタンプ>.AppImage
```
のようにしてはどうでしょうか。

### 定期的にリリースする

1, 2週間、長くとも一ヶ月単位で定期的にリリースします。リリースは自動化するのが好ましい。

### 最低限のドキュメントを整備する

すでに「最低限のドキュメント」は揃っています。ただし、Examples は日本語なので、余力があれば英語への翻訳を行いたいところです。

- Getting Started:
  - → https://github.com/thinreports/thinreports/issues/12 の「Getting Started」
- Examples:
  - → https://github.com/thinreports/thinreports-editor/tree/master/section-report#specifications-and-examples

これらを元に、thinreports/thinreports にドキュメントを整備します。

- README.md
  - Thinreports には二つのフォーマットが存在する
  - Basic Format と Section Format 
  - それぞれの概要と各ドキュメントへのリンク
- section-format/
  - getting-started.md
- basic-format.md
  - getting-started.md (OPTIONAL: 既存の http://www.thinreports.org/documentation/ja/getting-started/quickstart.html を引っ越す)

### 直近のゴールを決める

タスクを整理するためには、ゴールを決める必要があります。スコープはあまり欲張らず、ざっくり半年ぐらいで対応できそうなものにしておくと良いと思います。2022年1月リリースとか？

- どのバージョンで正式版を出すか
- そのバージョンでのスコープ (実装する機能) は何か
- Basic Format のそのバージョンでのスコープは何か

### ゴールとタスクを管理する

ゴールとスコープが決まったら、ある程度の粒度でタスクを列挙します。GitHub プロジェクトを使うのが良いと思います。また、`good for first task` も整理します。

**Comment by hidakatsuya** [comment]
@maeda-m ご確認くだされ〜

**Comment by hidakatsuya** [comment]
> 直近のゴールを決める
> * Basic Format のそのバージョンでのスコープは何か

Section Format のスコープとリリース予定日次第なところはありますが、Section Format の最初のリリースを  v1.0.0 とするなら、Basic Format は Custom font をいい加減対応できると良いなと思ってます。prawn (ttfunk) で `otf` がサポートされているので、Custom font が対応されると、かなり利用の幅が広がると思います。

**Comment by maeda-m** [comment]
@hidakatsuya いつもありがとうございます。


#12 で挙げられているように、持続可能な開発のために必要なことがまとめられており、素敵だと思います。


全体的に認識は合っていると思いますが、 "定期的にリリースする" については私の認識が曖昧です。

なんとなくリリースが自動化されていれば、定期的にリリースできそうだなーくらいのイメージを持っています。

定期的にリリースする目的が「作ったものをできるだけ早く使えるようにすること」とあるので、タスクや pullrequest 粒度が分かってきたら、もう少し認識が深まるのかなと思っています。


> Section Format のスコープとリリース予定日次第なところはありますが、Section Format の最初のリリースを v1.0.0 とするなら、Basic Format は Custom font をいい加減対応できると良いなと思ってます。

なるほど。この機会に対応したいですね。

**Comment by hidakatsuya** [comment]
@maeda-m 

> "定期的にリリースする" については私の認識が曖昧です。
> 定期的にリリースする目的が「作ったものをできるだけ早く使えるようにすること」とあるので、タスクや pullrequest 粒度が分かってきたら、もう少し認識が深まるのかなと思っています。

目的はその通りです。ナイトリービルド (あるいはデイリービルド) と言ったほうが適切だったかもしれません。

Chrome では Canary build などと呼ばれてますね。
https://www.google.com/chrome/canary/?platform=win64

ただ、開発スピードを考えると、毎日ビルドはあまり意味がないので、どちらかというと Dev channel の方が近いと思います。Dev channel は毎週更新だったと思う。
https://www.google.com/chrome/dev/?extra=devchannel&platform=win64

要は、開発の状態や安定性、進捗状況に関係なく、最新のパッケージをリリースするということです。

そこには、通常のリリースで行うような、動作確認やドキュメントの更新などは必要ないため、完全に自動化しても問題ないはずです。

**Comment by maeda-m** [comment]
@hidakatsuya 

> 要は、開発の状態や安定性、進捗状況に関係なく、最新のパッケージをリリースし利用可能な状態にするということです。

なるほど、ありがとうございます。
開発スピード次第ではありそうですが、定期リリースの意図について理解できました。

**Comment by hidakatsuya** [comment]
(@maeda-m )

> 直近のゴールを決める

のための GitHub Project を作りました。section format の正式版をリリースするバージョンは v1.0.0 を想定しています。
https://github.com/orgs/thinreports/projects/1

まだ途中ですが、まずはこんな感じの粒度でスコープを決めてはどうでしょうか。

**Comment by hidakatsuya** [comment]
ちなみに、https://github.com/orgs/thinreports/projects/1#card-65516521 あたりのドキュメントの方針ですが、いくつかの案を踏まえての以下の結論に基づいています。

- thinreports/thinreports の `docs/` でドキュメントを管理する
- www.thinreports.org/documentation のドキュメントもこちらに移行する
- www.thinreports.org/documentation は `docs/` へリダイレクトさせる

以下、検討したオプションと検討内容です。作業コストだけ考えれば「c. 現状の /documentation にコンテンツを追加する」がベストですが、

- 想定される短期的なドキュメントの数が少ないので、凝ったページやUIは必要ない
- 今後開発を進める上でドキュメントは最も修正しやすい形の方が良い

ということから、「a. thinreports/thinreports リポジトリに Markdown を直接おく」にしたいと思っています。

<Details>

- 想定される短中期的なドキュメント
  - Thinreportsとは
  - 二つのテンプレートフォーマットについて
    - それぞれの特徴
  - Section Format
    - Getting Started
      - Installation Guide
        - ない
      - Hello World
        - https://github.com/thinreports/thinreports/issues/12 の Getting Started (en)
    - Examples
      - https://github.com/thinreports/thinreports-editor/tree/master/section-report#specifications-and-examples (ja)
  - Basic Format
    - Getting Started
      - Installation Guide
        - https://www.thinreports.org/documentation/en/getting-started/installation.html (en/ja)
      - Hello World
        - https://www.thinreports.org/documentation/en/getting-started/quickstart.html (en/ja)
    - Examples
      - https://github.com/thinreports/thinreports-examples (en/ja)
    - API document
      - https://github.com/thinreports/thinreports-generator/blob/master/README.md (en)
- 選択肢
  - a. thinreports/thinreports リポジトリに Markdown を直接おく
    - README.md がルート
    - doc/section-format/getting-started.md, installation-guide.md など
    - 👍
      - 簡単、準備不要
    - 👎
      - 多言語対応が面倒
      - www.thinreports.org/documentation と重複する。統合するなら、当然移行も必要
  - b. thinreports/documentation (www.thinreports.org/documentation) におく
    - 現状、オレオレ jekyll サイトなので、mdBook などの静的ドキュメントサイトジェネレーターなど、何らかのツールやフレームワークを使って再構築したほうが良い
    - 👍
      - www.thinreports.org/documentation の URL を存続させることができる
      - 採用するツールによるが、多言語対応がしやすい
      - 将来、これを www.thinreports.org のコンテンツにしてしまっても良いと思う
    - 👎
      - 構築が大変で時間がかかる
      - コンテンツ量に対して too much 感はある
  - c. 現状の /documentation にコンテンツを追加する
    - 👍
      - 作業コストが一番低い
      - ドキュメントの場所(URL)も変わらないため影響もない
    - 👎
      - オレオレ jekyll なので恒久的には移行が必要。モチベーションがあがらない
      - サイトデザインが気に食わない（自分で作ったけど）

</Details>

**Comment by hidakatsuya** [comment]
@maeda-m 
v1.0.0 と v1.0.0-dev の最初のリリースまでのスコープを Project に整理してみました。ご意見ください。
https://github.com/orgs/thinreports/projects/1

**Comment by hidakatsuya** [comment]
最初に https://github.com/orgs/thinreports/projects/1#card-65594053 をやります。別途 issue を立てますね。

**Comment by hidakatsuya** [comment]
@maeda-m 

thx!

https://github.com/orgs/thinreports/projects/1#card-65814640 は Inbox ですが、どんな温度感ですか？個人的には v1.0.0 のスコープに入れても良いと思います。確かに、section-editor で basic-format の tlf を開く人は多そう。良さそうなら v1.0.0 に動かしておいてください。

**Comment by maeda-m** [comment]
@hidakatsuya 

> 確かに、section-editor で basic-format の tlf を開く人は多そう。

実は私がそうだったのです。

> 良さそうなら v1.0.0 に動かしておいてください。

v1.0.0 に移動しました。

**Comment by hidakatsuya** [comment]
@maeda-m thx! では、ロードマップとマイルストーンはこれで一旦決定として良いですか？

**Comment by maeda-m** [comment]
@hidakatsuya 

はい、追加はありません。

**Comment by hidakatsuya** [comment]
@maeda-m よーし、ではやっていきましょう。

さて、これらのタスクの管理はどんなふうにやっていきましょうか。何かイメージしてる方法がありますか？

**Comment by hidakatsuya** [comment]
@maeda-m 
私の案は次の通りです。

- トリアージするために作ったプロジェクト https://github.com/orgs/thinreports/projects/1 の名前を v1.0.0 などとし、引き続き使う
  - イメージしやすいように、すでに名前と説明は変更しちゃっています
- プロジェクトは v1.0.0-dev と v1.0.0 と Done のカラム（列）を持ち、完了したタスクは Done に移動して完了状態を管理する。着手状態は管理しない
  - v1.0.0-dev のカラムのタスクが全部捌けたら release ready ということになる
- 各タスクは、予め issue として作成しておく
  - プロジェクトを参照する人は少ないはず。issue として作成しておくことでコントリビュートしやすい
  - "Convert to issue" を使うと簡単に issue を作成でき、自動的に関連付けられる
  - ![image](https://user-images.githubusercontent.com/739339/127741294-9994f929-daee-4f0b-91be-44e573a02d86.png)
  - タスクの粒度が荒くてもとりあえず気にしない。ただし、ゴールを理解できるように、ある程度は背景や目的、ゴールについて説明を記載しておくこと。日本語でOKとする
- v1.0.0 へのタスクをプロジェクト https://github.com/orgs/thinreports/projects/1 で管理していることについて、thinreports/thinreports の README.md で説明しておく
  - Discussions でもアナウンスしておくと良いですね
- QA
  - 途中でタスクを追加したい場合は？
    - pull request を作成して、description やコメントで v1.0.0 に入れることを提案する
    - 入れることになったら、pull request をプロジェクトに紐付けておくとわかりやすいかもしれない
    - ![image](https://user-images.githubusercontent.com/739339/127741539-3559904d-016b-42e8-b5c3-8115aa63b241.png)
    - タスクが実装するものではなかったり、事前に相談したい場合は issue で提案を投げ、合意が取れたらプロジェクトにタスクを追加する

いかがでしょう？

なお、この手順にしたがって、https://github.com/orgs/thinreports/projects/1#card-65990772 の issue を作成しましたので、そちらも参考にしつつ内容を確認してください。よろしく！

**Comment by maeda-m** [comment]
@hidakatsuya 

> プロジェクトを参照する人は少ないはず。issue として作成しておくことでコントリビュートしやすい

なるほど、ありがとうございます。
良い案だと思います。

私はぼんやりとしたイメージとして、プロジェクトのカードを軸に issue や pull request を関連付けするイメージを持っていました。

たしかに、プロジェクトを参照する人は少なそうですね。

**Comment by hidakatsuya** [comment]
@maeda-m 
リポジトリに紐づくプロジェクトなら、まだ参照されやすいとは思います。なので、thinreports-generator, thinreports-editor, thinreports それぞれに `v1.0.0` のようなボードを作って、それぞれのタスクを管理するという方法もオプションとしてあります。

正直それが面倒だったのと、今回はドキュメントの整備など、実装以外のタスクも割とあるため、Organization に紐づくプロジェクトボードを使っています。これはとても便利なのですが、デメリットとして、このプロジェクトにたどり着くのが相対的に難しい、という点があります。

では、一旦私の提案の進め方でやってみましょうか。やりづらかったら、その都度改善していきましょう。

私がこの issue で話したかったことは一通り合意が取れたかなと思います。v1.0.0 の対応として何か他に気になる点や決めておきたい点がありますか？なければこの issue は閉じようと思います。

**Comment by maeda-m** [comment]
@hidakatsuya 

> それぞれのタスクを管理するという方法もオプションとしてあります。

なるほどー。今の Organization に紐づくプロジェクトがベストだと理解しました。

> v1.0.0 の対応として何か他に気になる点や決めておきたい点がありますか？なければこの issue は閉じようと思います。

はい。提案の内容で不安なところ等は無いので大丈夫だと思います。

**Comment by hidakatsuya** [comment]
@maeda-m
では、こちらも完了としますね

**Comment by hidakatsuya** [comment]
https://github.com/thinreports/thinreports/issues/23#issuecomment-890350179 の

> 各タスクは、予め issue として作成しておく

をまだやってなかったので reopen しました。それらが終わったら改めて close します。

**Comment by hidakatsuya** [comment]
@maeda-m 
v1.0.0 のうち、ドキュメントの整備や仕様の検討（カスタムフォント）を除いた実装系のタスの issue をそれぞれのリポジトリに作成しました。基本 Convert to issue しただけです。

また、カスタムフォントの実装の前段として、仕様を決めるタスクとして https://github.com/thinreports/thinreports/issues/5 を v1.0.0 リストに追加しました。

その他に issue を作成しておいた方が良いものがあれば作成してください。前述の通り、issue は最低限の内容なので、可能であれば、具体的な目的・仕様への更新などをやってもらえると嬉しいです。また、それによって着手しやすくなるので、コントリビュートの活性化にも繋がりますね。

とりあえず、この issue で私が話したい、やりたかったことはできたので、issue を close しますね。

本件について何か議題などあれば、気軽に reopen なりコメントなりしてください。
