### ISSUE TITLE
「従来の形式」と「新しい形式」に関連する用語を定義する

### ISSUE THREAD

**Issue by hidakatsuya** [thinreports/thinreports#24]
## 目的

現状では section と basic を区別する名称として section-report と basic-report が使われている。しかし、それぞれの editor の説明をするとき、例えば section 用の editor では「section形式のテンプレートを編集するためのエディタ」とした方が説明がしやすい。

section-report のリリースに向けて、この辺りの用語の曖昧さを解消しておいた方が良いと思う。実際、この状況だとドキュメントも書きづらい。

### 従来の形式

現在の thinreports (v0.12.0 以前) でサポートしている形式。

- レポートの出力タイプ
  - 「basic report」
- tlf のフォーマット
  - 「basic format」
- editor の名前
  - 「basic editor」

### 新しい形式

https://github.com/thinreports/thinreports/issues/7 で提案された新しい形式。

- レポートの出力タイプ
  - 「section report」
- tlf のフォーマット
  - 「section format」
- editor の名前
  - 「section editor」

## 用語の定義

https://github.com/orgs/thinreports/projects/1#card-65516247 で thinreports/thinreports の README.md に二つのレポートタイプについての説明を記載するときに、ここで定めている用語を使う必要があるため、それを持って定義とするぐらいでどうでしょう。

**Comment by hidakatsuya** [comment]
@maeda-m 
いかがでしょう。用語の提案内容だけでなく、他にも決めておいた方が良い「用語」が他にないかレビューしてください。

**Comment by hidakatsuya** [comment]
> * editor の名前
> * 「basic editor」

実際のパッケージ名にすると、

- ThinreportsBasicEditor
- ThinreportsSectionEditor

となるけど、

- ThinreportsEditorBasic, ThinreportsEditor-basic
- ThinreportsEditorSection, ThinreportsEditor-section

などの方がわかりやすい気がする。

**Comment by hidakatsuya** [comment]
> * editor の名前
> * 「basic editor」

https://github.com/thinreports/thinreports-editor/pull/103 で、editor のビルドパッケージ名は `ThinreportsEditor-<basic or section>-<version>-<platform>.<ext>` のようにしてみました。

**Comment by hidakatsuya** [comment]
@maeda-m 
なるほどなぁ。念の為確認ですが、その意図としては、section format / basic format いずれも拡張子が tlf だと、editor で開いてみない限りどちらのフォーマットのファイルかわからないから、ということであってますか？

良いかもしれないですね。ただ、その場合の section format の拡張子は、固有のものではなく `.json` で十分かなと思いました。独自の拡張子にしているメリットがあまり無い気がしてますし、`tlf` だと、デフォルトではエディタなどで JSON とし扱われないため、個別に設定が必要になってしまいます。強いてメリットをあげるなら、ファイルを開くときに `tlf` でフィルタできるので選択しやすい、というのはあるかもしれない。

**Comment by hidakatsuya** [comment]
> パッケージ名も含めて、用語の提案内容でよいと思います。

thx! では、用語については description の内容で進めることにしましょう。

**Comment by maeda-m** [comment]
@hidakatsuya 

> どちらのフォーマットのファイルかわからないから、ということであってますか？

はい。その意図であっています。

> 固有のものではなく `.json` で十分かなと思いました。

たしかに！その通りですね。

> では、用語については description の内容で進めることにしましょう。

はい。ひとまず用語については追加はありません。

拡張子については、用語を扱うこの issue の範囲とズレてしまいました。
※ いろいろ整理いただいたので助かります。

**Comment by hidakatsuya** [comment]
@maeda-m 
では、この issue は完了としますね。拡張子については v1.0.0-dev リストにタスクを作っておくので、そちらで検討しましょう。
