### ISSUE TITLE
ThinReports::Errors::UnknownEventType for footer_insert

### ISSUE THREAD

**Issue by dtrce** [thinreports/thinreports#6]
I'm using thinreports 0.7.7 and I am trying to set the footer fields with the following code. 

```
report.events.on :footer_insert do |e|
     e.page.item(:amt_total).value("0.0")
end
```

I'm getting an error though "ThinReports::Errors::UnknownEventType". 

I've also tried the following code but getting "undefined method `on_footer_insert' for #<ThinReports::Core::Shape::List::Page:0x007fafef3b0e38>" error

```
report.list do |list|
      list.on_footer_insert do |footer|
        footer.item(:amt_total).value("0.9")
      end
end
```

**Comment by hidakatsuya** [comment]
@dtrce 
Please refer to [Example: Advanced List in 0.7.x](https://github.com/thinreports/thinreports-examples/tree/0.7/list/advanced).
