### ISSUE TITLE
Windows環境でPDFが出力されない

### ISSUE THREAD

**Issue by tunagle** [thinreports/thinreports#8]
Windows環境でThinreportsでPDF出力すると、エラー(Permission denied)となり、出力できない。

[環境]
thinreports-0.10.3
Windows 8

[ソース]
```
   report = Thinreports::Report.new(layout: "#{Rails.root}/app/pdfs/order_report.tlf") 
   report.start_new_page
      :
   report.generate(filename: store_filepath) 　←ここでエラー

```
[エラーメッセージ]
"Permission denied @ apply2files - C:/Users/nxxxx/3982AppData/Local/Temp/temp-image*"

[原因]
出力の際作成される中間ファイルをクローズしていない為、
削除する時にエラーとなる

[対応]
{Rails.root}\vendor\bundle\ruby\2.5.0\gems\thinreports-0.10.3\lib\thinreports\generator\pdf\document\graphics\image.rb

        def clean_temp_images
          `temp_image_registry.each_value` do |image_path|
             File.delete(image_path) if File.exist?(image_path) 　←※
          end
        end

※の行を以下に変更
           **image_path.close! if File.exist?(image_path)**

**Comment by hidakatsuya** [comment]
ご報告ありがとうございます。また、大変遅くなってしまいすみません。

恐らくこれは、thinreports の内部で使っている prawn の問題ではないかと思います。
https://github.com/prawnpdf/prawn/pull/1090

上記修正が prawn 2.3 で取り込まれているため、prawn 2.3 を使っていただくことで解決するのではないかと思います。以下のように、Gemfile で利用する prawn のバージョンを明示してみてください。

Gemfile
```diff
gem 'thinreports'
+ gem 'prawn', '>= 2.3'
```

かなり時間も経過していますので、一度カードは close させてもらいますが、もし何かありましたら、気軽に reopen してください。
